/*
 * PICSIMGUI.java
 *
 * Created on April 7, 2008, 1:50 PM
 */
package my.PICSIMGUI;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.lang.String;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;

/**
 *
 * @author  Mogli BA
 */
public class PICSIMGUI extends javax.swing.JFrame {

    /** Creates new form PICSIMGUI */
    public PICSIMGUI() {
        super("PIC16F84 - SIMULATOR");
        initComponents();
    }

    /*  static public void echo(String s, boolean b = true) {
    System.out.print(s);
    }
     */
    static public void e(Object... parameters) {
        if (parameters.length == 2) {
            System.out.print(parameters[0]);
        } else {
            System.out.print(parameters[0]);
        }
    }

    private static void selectRow(int row, JTextArea area) {
        int start = -1, end = -1;
        try {
            start = area.getLineStartOffset(row);
            end = area.getLineEndOffset(row);
            area.setSelectionStart(start);
            area.setSelectionEnd(end);
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        }
    }

    public void setPortARadios(int[] port, int portValue) {

        TextFieldPortAValue.setText(String.valueOf(portValue));

        if (port[0] == 1) {
            RadioButtonA0.setSelected(true);
        } else {
            RadioButtonA0.setSelected(false);
        }
        if (port[1] == 1) {
            RadioButtonA1.setSelected(true);
        } else {
            RadioButtonA1.setSelected(false);
        }
        if (port[2] == 1) {
            RadioButtonA2.setSelected(true);
        } else {
            RadioButtonA2.setSelected(false);
        }
        if (port[3] == 1) {
            RadioButtonA3.setSelected(true);
        } else {
            RadioButtonA3.setSelected(false);
        }
        if (port[4] == 1) {
            RadioButtonA4.setSelected(true);
        } else {
            RadioButtonA4.setSelected(false);
        }
        if (port[5] == 1) {
            RadioButtonA5.setSelected(true);
        } else {
            RadioButtonA5.setSelected(false);
        }
        if (port[6] == 1) {
            RadioButtonA6.setSelected(true);
        } else {
            RadioButtonA6.setSelected(false);
        }
        if (port[7] == 1) {
            RadioButtonA7.setSelected(true);
        } else {
            RadioButtonA7.setSelected(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonRun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPortsFlags = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelPorts = new javax.swing.JPanel();
        LabelPortA = new javax.swing.JLabel();
        LabelPortB = new javax.swing.JLabel();
        RadioButtonA7 = new javax.swing.JRadioButton();
        RadioButtonA6 = new javax.swing.JRadioButton();
        RadioButtonA5 = new javax.swing.JRadioButton();
        RadioButtonA4 = new javax.swing.JRadioButton();
        RadioButtonA3 = new javax.swing.JRadioButton();
        RadioButtonA2 = new javax.swing.JRadioButton();
        RadioButtonA1 = new javax.swing.JRadioButton();
        RadioButtonA0 = new javax.swing.JRadioButton();
        RadioButtonB0 = new javax.swing.JRadioButton();
        RadioButtonB1 = new javax.swing.JRadioButton();
        RadioButtonB2 = new javax.swing.JRadioButton();
        RadioButtonB3 = new javax.swing.JRadioButton();
        RadioButtonB4 = new javax.swing.JRadioButton();
        RadioButtonB5 = new javax.swing.JRadioButton();
        RadioButtonB6 = new javax.swing.JRadioButton();
        RadioButtonB7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        TextFieldPortAValue = new javax.swing.JTextField();
        PanelFlags = new javax.swing.JPanel();
        LabelZFlag = new javax.swing.JLabel();
        LabelCarryFlag = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InputTextFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonRun.setText("Start");
        ButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRunActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelPorts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));

        LabelPortA.setText("Port A");

        LabelPortB.setText("Port B");

        jLabel3.setText("   7     6     5     4     3     2     1     0");

        TextFieldPortAValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextFieldPortAValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPortAValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPortsLayout = new javax.swing.GroupLayout(PanelPorts);
        PanelPorts.setLayout(PanelPortsLayout);
        PanelPortsLayout.setHorizontalGroup(
            PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortsLayout.createSequentialGroup()
                .addGroup(PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPortsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelPortA)
                            .addComponent(LabelPortB))
                        .addGap(11, 11, 11)
                        .addGroup(PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPortsLayout.createSequentialGroup()
                                .addComponent(RadioButtonA7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonA0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldPortAValue, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addGroup(PanelPortsLayout.createSequentialGroup()
                                .addComponent(RadioButtonB7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButtonB0)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPortsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        PanelPortsLayout.setVerticalGroup(
            PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RadioButtonA0)
                    .addComponent(RadioButtonA1)
                    .addComponent(RadioButtonA2)
                    .addComponent(RadioButtonA3)
                    .addComponent(RadioButtonA4)
                    .addComponent(RadioButtonA5)
                    .addComponent(RadioButtonA6)
                    .addComponent(RadioButtonA7)
                    .addComponent(LabelPortA)
                    .addComponent(TextFieldPortAValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(PanelPortsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPortB)
                    .addComponent(RadioButtonB0)
                    .addComponent(RadioButtonB1)
                    .addComponent(RadioButtonB3)
                    .addComponent(RadioButtonB4)
                    .addComponent(RadioButtonB5)
                    .addComponent(RadioButtonB6)
                    .addComponent(RadioButtonB7)
                    .addComponent(RadioButtonB2))
                .addContainerGap())
        );

        PanelFlags.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status Flags", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));

        LabelZFlag.setText("Z-Flag");

        LabelCarryFlag.setText("Carry");

        javax.swing.GroupLayout PanelFlagsLayout = new javax.swing.GroupLayout(PanelFlags);
        PanelFlags.setLayout(PanelFlagsLayout);
        PanelFlagsLayout.setHorizontalGroup(
            PanelFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFlagsLayout.createSequentialGroup()
                .addGroup(PanelFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelZFlag)
                    .addComponent(LabelCarryFlag))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelFlagsLayout.setVerticalGroup(
            PanelFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFlagsLayout.createSequentialGroup()
                .addComponent(LabelZFlag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCarryFlag)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPortsFlagsLayout = new javax.swing.GroupLayout(PanelPortsFlags);
        PanelPortsFlags.setLayout(PanelPortsFlagsLayout);
        PanelPortsFlagsLayout.setHorizontalGroup(
            PanelPortsFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortsFlagsLayout.createSequentialGroup()
                .addGroup(PanelPortsFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPortsFlagsLayout.createSequentialGroup()
                        .addComponent(PanelFlags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        PanelPortsFlagsLayout.setVerticalGroup(
            PanelPortsFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPortsFlagsLayout.createSequentialGroup()
                .addComponent(PanelPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPortsFlagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPortsFlagsLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPortsFlagsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PanelFlags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ports and Flags", PanelPortsFlags);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Adresse", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        InputTextFileButton.setText("Load File");
        InputTextFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputTextFileButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRun)
                    .addComponent(InputTextFileButton))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Ports and Flags");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings("static-access")
    private void ButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRunActionPerformed

        ButtonRun.setText("Stop");

        InstructionInterpreter interpret = new InstructionInterpreter(jTextArea1.getText().split("\n"));
        for (int i = 0; i <= (jTextArea1.getText().split("\n").length - 1); i++) {
            try {

                selectRow(i, jTextArea1);

                int ret = interpret.translateCodeLine(i);
                if (ret != -2 && ret != -1) {
                    i = ret;
                }
                if (ret == -1) {
                    System.err.println("Error in line " + i);
                    break;
                }
                setPortARadios(interpret.pic.getPortA(), interpret.pic.memory[5]);

                Thread.currentThread().sleep(100); //sleep for 1000 ms
            } catch (InterruptedException ex) {
                Logger.getLogger(PICSIMGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
}//GEN-LAST:event_ButtonRunActionPerformed

    private void TextFieldPortAValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPortAValueActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPortAValueActionPerformed

    @SuppressWarnings("static-access")
    private void InputTextFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTextFileButtonActionPerformed

        String initialDirectory = "";
        String fileURL = null;
        JFileChooser chooser;
        int returnVal;

        chooser = new JFileChooser(initialDirectory);
        returnVal = chooser.showOpenDialog((Component) evt.getSource());

        if (returnVal == chooser.APPROVE_OPTION) {
            /* To create a URL for a file on the local file-system, we simply
             * pre-pend the "file" protocol to the absolute path of the file.
             */
            fileURL = chooser.getSelectedFile().getAbsolutePath();
        //echo(fileURL);
        }


        String record = null;

        try {

            jTextArea1.setText("");

            FileReader fr = new FileReader(fileURL);
            BufferedReader br = new BufferedReader(fr);

            record = new String();
            while ((record = br.readLine()) != null) {
                //System.out.println(record);
                jTextArea1.append(record + "\n");
            }
        // InstructionInterpreter interpret = new InstructionInterpreter(recordArray);
        //return recordArray;
        } catch (IOException e) {
            // catch possible io errors from readLine()
            System.out.println("Uh oh, got an IOException error!");
            e.printStackTrace();
        }

}//GEN-LAST:event_InputTextFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PICSIMGUI().setVisible(true);
                PicCPU test = new PicCPU();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRun;
    private javax.swing.JButton InputTextFileButton;
    private javax.swing.JLabel LabelCarryFlag;
    private javax.swing.JLabel LabelPortA;
    private javax.swing.JLabel LabelPortB;
    private javax.swing.JLabel LabelZFlag;
    private javax.swing.JPanel PanelFlags;
    private javax.swing.JPanel PanelPorts;
    private javax.swing.JPanel PanelPortsFlags;
    private javax.swing.JRadioButton RadioButtonA0;
    private javax.swing.JRadioButton RadioButtonA1;
    private javax.swing.JRadioButton RadioButtonA2;
    private javax.swing.JRadioButton RadioButtonA3;
    private javax.swing.JRadioButton RadioButtonA4;
    private javax.swing.JRadioButton RadioButtonA5;
    private javax.swing.JRadioButton RadioButtonA6;
    private javax.swing.JRadioButton RadioButtonA7;
    private javax.swing.JRadioButton RadioButtonB0;
    private javax.swing.JRadioButton RadioButtonB1;
    private javax.swing.JRadioButton RadioButtonB2;
    private javax.swing.JRadioButton RadioButtonB3;
    private javax.swing.JRadioButton RadioButtonB4;
    private javax.swing.JRadioButton RadioButtonB5;
    private javax.swing.JRadioButton RadioButtonB6;
    private javax.swing.JRadioButton RadioButtonB7;
    private javax.swing.JTextField TextFieldPortAValue;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
